### ISSUE TITLE
world signal shutdown crash

### ISSUE THREAD

**Issue by xackery** [EQEmu/Server#2429]
```
[World] [Info] [main.cpp::CatchSignal:461] Caught signal [15]
[World] [Info] [main.cpp::main:449] World main loop completed
[World] [Info] [main.cpp::main:450] Shutting down zone connections (if any)
[World] [Info] [main.cpp::main:452] Zone (TCP) listener stopped
[World] [Info] [main.cpp::main:453] Signaling HTTP service to stop
30	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
[World] [Crash] [crash.cpp::print_trace:218] stack trace for /home/eqemu/code/build/bin/world pid=978365
[World] [Crash] [crash.cpp::print_trace:218] [New LWP 978366]
[World] [Crash] [crash.cpp::print_trace:218] [New LWP 978367]
[World] [Crash] [crash.cpp::print_trace:218] [New LWP 978368]
[World] [Crash] [crash.cpp::print_trace:218] [New LWP 978369]
[World] [Crash] [crash.cpp::print_trace:218] [Thread debugging using libthread_db enabled]
[World] [Crash] [crash.cpp::print_trace:218] Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[World] [Crash] [crash.cpp::print_trace:218] 0x00007fa8298490ca in __waitpid (pid=978411, stat_loc=stat_loc@entry=0x0, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
[World] [Crash] [crash.cpp::print_trace:218] [Current thread is 1 (Thread 0x7fa828b6f140 (LWP 978365))]
[World] [Crash] [crash.cpp::print_trace:218] #0  0x00007fa8298490ca in __waitpid (pid=978411, stat_loc=stat_loc@entry=0x0, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
[World] [Crash] [crash.cpp::print_trace:218] #1  0x000055d1dacedc2a in print_trace () at /home/eqemu/code/common/crash.cpp:213
[World] [Crash] [crash.cpp::print_trace:218] #2  <signal handler called>
[World] [Crash] [crash.cpp::print_trace:218] #3  0x00007ffd7a8f7a10 in ?? ()
[World] [Crash] [crash.cpp::print_trace:218] #4  0x000055d1dae74617 in std::function<void (std::shared_ptr<EQ::Net::DaybreakConnection>, EQ::Net::DbProtocolStatus, EQ::Net::DbProtocolStatus)>::operator()(std::shared_ptr<EQ::Net::DaybreakConnection>, EQ::Net::DbProtocolStatus, EQ::Net::DbProtocolStatus) const (__args#2=<optimized out>, __args#1=<optimized out>, __args#0=std::shared_ptr<class EQ::Net::DaybreakConnection> (empty) = {...}, this=<optimized out>) at /usr/include/c++/8/bits/std_function.h:682
[World] [Crash] [crash.cpp::print_trace:218] #5  EQ::Net::DaybreakConnection::ChangeStatus (this=0x55d1db383970, new_status=EQ::Net::StatusDisconnecting) at /home/eqemu/code/common/net/daybreak_connection.cpp:894
[World] [Crash] [crash.cpp::print_trace:218] #6  0x000055d1dac137e6 in Client::~Client (this=0x55d1db3359b0, __in_chrg=<optimized out>) at /home/eqemu/code/world/client.cpp:136
[World] [Crash] [crash.cpp::print_trace:218] #7  0x000055d1dac354e9 in ListElement<Client*>::~ListElement (this=0x55d1db334390, __in_chrg=<optimized out>) at /home/eqemu/code/world/../common/linked_list.h:332
[World] [Crash] [crash.cpp::print_trace:218] #8  0x000055d1dac35560 in LinkedList<Client*>::Clear (this=0x55d1dafac000 <client_list>) at /home/eqemu/code/world/../common/linked_list.h:63
[World] [Crash] [crash.cpp::print_trace:218] #9  0x00007fa82937ad8c in __run_exit_handlers (status=0, listp=0x7fa8294fb718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
[World] [Crash] [crash.cpp::print_trace:218] #10 0x00007fa82937aeba in __GI_exit (status=<optimized out>) at exit.c:139
[World] [Crash] [crash.cpp::print_trace:218] #11 0x00007fa8293650a2 in __libc_start_main (main=0x55d1dabf59e0 <main(int, char**)>, argc=1, argv=0x7ffd7a8f7bf8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd7a8f7be8) at ../csu/libc-start.c:342
[World] [Crash] [crash.cpp::print_trace:218] #12 0x000055d1dac08caa in _start () at /usr/include/c++/8/ext/new_allocator.h:79
[World] [Crash] [crash.cpp::print_trace:218] [Inferior 1 (process 978365) detached]
```

**Comment by xackery** [comment]
Above is likely part of akka's branch though

**Comment by Akkadius** [comment]
> Above is likely part of akka's branch though

Not necessarily

**Comment by Kinglykrab** [comment]
What exactly was going on here? @xackery

**Comment by xackery** [comment]
Considering it happened so long ago, I have no idea. I think I just dumped a crash, this was before akka's telemetry.
